//--featured poem--------------*//
var urls2 = [
	"./featured/A Birthday.html",
	"./featured/A Child Of Mine.html",
	"./featured/A Father's Prayer.html",
	"./featured/A Man's Requirements.html",
	"./featured/A Prayer.html",
	"./featured/A Word to Husbands.html",
	"./featured/Advice To A Son.html",
	"./featured/An Empty Meadow.html",
	"./featured/Are You There.html",
	"./featured/Be The Best Of Whatever You Are.html",
	"./featured/Because I Could Not Stop for Death.html",
	"./featured/Calypso.html",
	"./featured/Courage.html",
	"./featured/Courage_JS.html",
	"./featured/Death Alone.html",
	"./featured/Deep-sea Soundings.html",
	"./featured/Denouement Villanelle.html",
	"./featured/Desiderata.html",
	"./featured/Do Not Go Gentle Into That Good Night.html",
	"./featured/Faith.html",
	"./featured/Fire and Ice.html",
	"./featured/For My Daughter.html",
	"./featured/For the Traveler.html",
	"./featured/Freedom.html",
	"./featured/Go to the Limits of Your Longing.html",
	"./featured/Have You Earned Your Tomorrow.html",
	"./featured/Hearthside.html",
	"./featured/Hello, Dracula.html",
	"./featured/How Do I Love Thee.html",
	"./featured/I Am the Only Being Whose Doom.html",
	"./featured/I Do Not Love You Except Because I Love You.html",
	"./featured/I Love You.html",
	"./featured/I Slept....html",
	"./featured/I Want A Life Measured.html",
	"./featured/I Want To Be.html",
	"./featured/If.html",
	"./featured/If God Says Yes.html",
	"./featured/If I Can Stop One Heart From Breaking.html",
	"./featured/If I Could Tell You.html",
	"./featured/Immortality.html",
	"./featured/Into the Fray.html", 
	"./featured/Invictus.html", 
	"./featured/Keep Going.html", 
	"./featured/Later Today.html",
	"./featured/Let Her Remember.html",
	"./featured/Love's Language.html",
	"./featured/Mad Girl's Love Song.html",
	"./featured/May She Always Know.html",
	"./featured/My Creed.html",
	"./featured/Myself.html",
	"./featured/Not.html",
	"./featured/Our Little Ghost.html",
	"./featured/Pain Ends.html",
	"./featured/Perfect Woman.html",
	"./featured/Provisions.html",
	"./featured/Remember.html",
	"./featured/Sea Fever.html",
	"./featured/See It Through.html",
	"./featured/See What I See.html",
	"./featured/She Walks in Beauty.html",
	"./featured/Song of the Open Road.html",
	"./featured/Sonnet 18 Shall I compare thee to a summer’s day.html",
	"./featured/Sonnet 116 Let Me Not To The Marriage of True Minds.html",
	"./featured/Sonnet VII.html",
	"./featured/Still I Rise.html",
	"./featured/Stopping by Woods on a Snowy Evening.html",
	"..featured/Sweet Sixteen.html",
	"./featured/The Bells.html",
	"./featured/The Comfort Zone.html",
	"./featured/The Guy in the Glass.html",
	"./featured/The Invitation.html",
	"./featured/The Journey.html",
	"./featured/The Night is Darkening Round Me.html",
	"./featured/The Road Not Taken.html",
	"./featured/The Spring And The Fall.html",
	"./featured/The Summer Girl.html",
	"./featured/The True Meaning Of Life.html",
	"./featured/The Visitor.html",
	"./featured/Time Does Not Bring Relief; You All Have Lied.html",
	"./featured/To A Little Girl.html",
	"./featured/To My Daughter, With Love.html",
	"./featured/To My Valentine.html",
	"./featured/Travel.html",
	"./featured/Trees.html",
	"./featured/Untitled.html",
	"./featured/What Life Should Be.html",
	"./featured/What Lips My Lips Have Kissed.html",
	"./featured/Wild nights - Wild nights.html",
	"./featured/You Start Dying Slowly.html",
	"./featured/You Took Away My Innocence.html",
	"./featured/You Were Born with Potential.html"
	];
var myIframe2 = document.getElementById("poemIframe");
function displayRandomFile2() 
	{
		var randomSelectedUrl2 = urls2[Math.floor(Math.random() * urls2.length)];
		myIframe2.src = randomSelectedUrl2;
	}
displayRandomFile2();
setInterval(displayRandomFile2, 100000);
//--END featured poem----------*//
